### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by santosh653**
Thanks for the code, its working good.
Added Architecture "ppc64le"

### CODE REVIEW

**Comment by osallou** [comment]
@santosh653 what is purpose of this PR? you only specify ppc64 arch, disabling amd64 arch.

**Comment by santosh653** [comment]
Adding power support ppc64le.
This is part of the Ubuntu distribution for ppc64le. This helps us simplify testing later when distributions are re-building and re-releasing. For more info tag @gerrith3

**Comment by osallou** [comment]
ok, but setting arch: ppc set the build only for this arch, it does not add it.

I don't mind getting build for ppc too, but amd64 should be kept in the  build matrix....

**Comment by gerrith3** [comment]
@santosh653 you'll need to update your patch - this should build for both ppc64le and for amd64 - you shut off one and enabled the other as @osallou pointed out.  Please get an extra review before submitting just to make sure this is cleaned up.

**Comment by santosh653** [comment]
Hi.,
This is built successfully for both ppc64le & amd64.
Please refer the link below,
https://travis-ci.com/github/santosh653/biomaj-core

**Comment by osallou** [comment]
@santosh653 , merged! thanks

**Comment by santosh653** [comment]
Thank you, @osallou  & @gerrith3

**Pull request merged**
